"""Local-only coding RAG assistant."""

from __future__ import annotations

from pathlib import Path

import requests

from .archive import AnswerArchive
from .local_model import HybridLocalCodeModel
from .rag import RagStore
from .web import WebResearcher
from .memory import MemoryStore


class LocalCodingAssistant:
    def __init__(self, data_dir: Path | str = "data") -> None:
        self.data_dir = Path(data_dir)
        self.rag_path = self.data_dir / "rag_store.json"
        self.model = HybridLocalCodeModel.load(self.data_dir)
        self.rag = RagStore.load(self.rag_path)
        self.web = WebResearcher()
        self.archive = AnswerArchive(self.data_dir)
        self.memory = MemoryStore(self.data_dir)

    def ingest_text(self, text: str, *, source: str, title: str = "") -> tuple[int, int]:
        chunks = self.rag.add_text(text, source=source, title=title)
        tokens = self.model.train_text(text)
        self.save()
        return chunks, tokens

    def ingest_file(self, path: Path) -> tuple[int, int]:
        text = path.read_text(encoding="utf-8", errors="ignore")
        return self.ingest_text(text, source=str(path), title=path.name)

    def ingest_directory(self, path: Path) -> tuple[int, int, int]:
        allowed = {
            ".py",
            ".js",
            ".ts",
            ".tsx",
            ".jsx",
            ".java",
            ".go",
            ".rs",
            ".cpp",
            ".c",
            ".h",
            ".md",
            ".txt",
            ".json",
            ".yaml",
            ".yml",
            ".toml",
        }
        files = 0
        chunks = 0
        tokens = 0
        ignored_dirs = {".venv", "__pycache__", ".git", "data"}
        for file_path in path.rglob("*"):
            if ignored_dirs.intersection(file_path.parts) or not file_path.is_file():
                continue
            if file_path.suffix.lower() not in allowed:
                continue
            file_chunks, file_tokens = self.ingest_file(file_path)
            files += 1
            chunks += file_chunks
            tokens += file_tokens
        return files, chunks, tokens

    def research_web(self, query: str, *, limit: int = 4) -> int:
        added = 0
        for result in self.web.search(query, limit=limit):
            combined = f"{result.title}\n{result.snippet}\n"
            try:
                page_text = self.web.fetch_text(result.url)
            except requests.RequestException:
                page_text = ""
            text = combined + "\n" + page_text[:8000]
            chunks, _ = self.ingest_text(text, source=result.url, title=result.title)
            added += chunks
        return added

    def answer(self, question: str, *, use_web: bool = True) -> str:
        if use_web:
            try:
                self.research_web(f"{question} programming solution", limit=3)
            except Exception as exc:
                web_note = f"Internet research failed: {exc}"
            else:
                web_note = "Internet research completed."
        else:
            web_note = "Internet research skipped."

        # Fetch relevant local database context
        hits = self.rag.search(question, limit=5)
        context_list = []
        for _, doc in hits:
            context_list.append(f"Source: {doc.title} ({doc.source})\n{doc.text}")
        context = "\n\n".join(context_list)

        # Retrieve structured conversational history
        chat_history = self.memory.get_chat_history(limit=8)
        history_str = ""
        for turn in chat_history:
            role = "User" if turn["role"] == "user" else "Jarvis"
            history_str += f"{role}: {turn['content']}\n"

        # Construct conversational system-prompted context template
        prompt = (
            "You are JARVIS, an elite conversational AI software engineer and system assistant.\n"
            "Ground your responses in the provided local context and multi-turn history. Deliver highly technical,\n"
            "accurate, and human-like answers. Do NOT list raw database records or score values; synthesize naturally.\n\n"
        )
        if context:
            prompt += f"CONTEXT FROM LOCAL MEMORY:\n{context}\n\n"
        if history_str:
            prompt += f"CONVERSATION HISTORY:\n{history_str}\n"
        
        prompt += f"User: {question}\nJarvis:"

        generated = self.model.complete(prompt, max_tokens=380, temperature=0.7)
        
        # Clean potential leading/trailing tags or role markers generated by some models
        generated_clean = generated.strip()
        if generated_clean.startswith("Jarvis:"):
            generated_clean = generated_clean[len("Jarvis:"):].strip()
            
        answer = self._compose_answer(question, hits, generated_clean, web_note)
        
        # Save to archive and memory silently
        self.archive.save_answer(question, answer, source="coding-assistant")
        self.ingest_text(
            f"Question: {question}\nAnswer:\n{answer}",
            source="jarvis-answer-archive",
            title="Saved Jarvis answer",
        )
        return answer

    def save(self) -> None:
        self.data_dir.mkdir(parents=True, exist_ok=True)
        self.model.save()
        self.rag.save()

    def train_transformer_corpus(
        self,
        corpus_path: Path,
        *,
        epochs: int,
        batch_size: int,
        learning_rate: float,
        steps_per_epoch: int,
    ) -> dict[str, float | int]:
        return self.model.train_transformer_corpus(
            corpus_path,
            epochs=epochs,
            batch_size=batch_size,
            learning_rate=learning_rate,
            steps_per_epoch=steps_per_epoch,
        )

    @staticmethod
    def _compose_answer(question: str, hits, generated: str, web_note: str) -> str:
        useful_generated = len(generated.strip().split()) >= 8
        if useful_generated:
            return generated

        lines = [
            "# Local Coding Answer",
            "",
            f"Problem: {question}",
            "",
            "## Approach",
            "- Retrieved the most relevant local/web knowledge from the RAG store.",
            "- Built the response from retrieved coding context and the local trained model state.",
            "- Local model generation is not useful yet; using RAG-grounded fallback.",
            "",
            "## Suggested Solution"
        ]
        lines.extend(LocalCodingAssistant._grounded_solution(question, hits))
        if hits:
            lines.extend(["", "## Evidence"])
            for score, doc in hits:
                excerpt = doc.text[:450].strip()
                lines.append(f"- {doc.title} | score={score:.3f} | {doc.source}\n  {excerpt}")
        lines.extend(["", f"Status: {web_note}"])
        return "\n".join(lines)

    @staticmethod
    def _looks_useful(text: str) -> bool:
        if len(text.split()) < 12:
            return False
        if len(text.split()) > 30 and not any(mark in text for mark in {".", ":", ";", "\n"}):
            return False
        if text.count('"') > 6 or text.count("< /") or text.count(" self.") > 3:
            return False
        if text.count(" = ") > 5 or text.count(" . ") > 4:
            return False
        words = text.lower().split()
        unique_ratio = len(set(words)) / max(len(words), 1)
        if unique_ratio < 0.55:
            return False
        alpha_words = [word for word in text.split() if any(char.isalpha() for char in word)]
        lowercase_words = [word for word in alpha_words if word[:1].islower()]
        if len(alpha_words) > 20 and len(lowercase_words) / len(alpha_words) > 0.9:
            return False
        punctuation_ratio = sum(1 for char in text if char in "{}[]()<>?*=|") / max(len(text), 1)
        if punctuation_ratio > 0.16:
            return False
        repeated_fragments = text.count(" self.") + text.count(" = ") + text.count(" -> ")
        return repeated_fragments < 18

    @staticmethod
    def _grounded_solution(question: str, hits) -> list[str]:
        lowered = question.lower()
        top_sources = [doc for _, doc in hits[:3]]
        source_names = ", ".join(doc.title for doc in top_sources) or "the indexed project files"

        if any(word in lowered for word in {"command", "cli", "argument", "argparse"}):
            return [
                f"Use the CLI pattern already present in {source_names}.",
                "",
                "1. Add a new subparser inside `build_parser()`.",
                "2. Implement a small function that performs the command work.",
                "3. Add an `elif args.command == \"your-command\"` branch in `main()`.",
                "4. Run `python main.py train .` again so the assistant learns the new code.",
            ]

        if "transformer" in lowered or ("train" in lowered and "model" in lowered):
            return [
                "Put high-quality coding examples in the `corpus/` folder first.",
                "Run `.venv\\Scripts\\python.exe main.py train-transformer corpus --epochs 3 --steps-per-epoch 150`.",
                "For a quick smoke test, use fewer steps; for better answers, use a larger curated corpus and more epochs.",
                "The trained checkpoint is saved in `data/transformer_code_model.pt` and is used automatically by `ask`.",
            ]

        if any(word in lowered for word in {"error", "exception", "traceback", "modulenotfounderror"}):
            return [
                "Start from the exact traceback and identify the first line that belongs to your project.",
                "Check whether the failing import/function exists in the retrieved source files.",
                "After changing the code, run compile/test commands and train the assistant again on the updated project.",
            ]

        if top_sources:
            return [
                f"The strongest matching context is in {source_names}.",
                "Read the evidence below, apply the same local patterns, then retrain the assistant with `python main.py train .`.",
                "The local generator needs more coding examples before it can produce detailed original code reliably.",
            ]

        return [
            "No relevant context is indexed yet.",
            "Train first with `python main.py train <file-or-folder>`, then ask again.",
        ]
